config gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y_cfg;
		design gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.mm_bridge_0_m0_translator use gidel_hawkeye_pcie_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.onchip_memory2_0_s1_translator use gidel_hawkeye_pcie_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.mm_bridge_0_m0_agent use gidel_hawkeye_pcie_altera_merlin_master_agent_181.altera_merlin_master_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.onchip_memory2_0_s1_agent use gidel_hawkeye_pcie_altera_merlin_slave_agent_181.altera_merlin_slave_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.onchip_memory2_0_s1_agent_rsp_fifo use gidel_hawkeye_pcie_altera_avalon_sc_fifo_181.altera_avalon_sc_fifo;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.router use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_rimmbqy;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.router_001 use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_v2xnjyq;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.cmd_demux use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_fkf75ui;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.cmd_mux use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_ambf7wa;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.rsp_demux use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_fkf75ui;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.rsp_mux use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_byxvdyi;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.onchip_memory2_0_s1_cmd_width_adapter use gidel_hawkeye_pcie_altera_merlin_width_adapter_181.altera_merlin_width_adapter;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.onchip_memory2_0_s1_rsp_width_adapter use gidel_hawkeye_pcie_altera_merlin_width_adapter_181.altera_merlin_width_adapter;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_amcw57y.avalon_st_adapter use gidel_hawkeye_pcie_altera_avalon_st_adapter_181.gidel_hawkeye_pcie_altera_avalon_st_adapter_181_f3s2n2q;
endconfig

