config gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq_cfg;
		design gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.pcie_a10_hip_0_dma_wr_master_translator use gidel_hawkeye_pcie_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.onchip_memory2_0_s2_translator use gidel_hawkeye_pcie_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.pcie_a10_hip_0_dma_wr_master_agent use gidel_hawkeye_pcie_altera_merlin_master_agent_181.altera_merlin_master_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.onchip_memory2_0_s2_agent use gidel_hawkeye_pcie_altera_merlin_slave_agent_181.altera_merlin_slave_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.onchip_memory2_0_s2_agent_rsp_fifo use gidel_hawkeye_pcie_altera_avalon_sc_fifo_181.altera_avalon_sc_fifo;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.router use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_w3ngpsa;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.router_001 use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_ej3oh4i;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.onchip_memory2_0_s2_burst_adapter use gidel_hawkeye_pcie_altera_merlin_burst_adapter_181.altera_merlin_burst_adapter;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.cmd_demux use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_2ewhqri;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.cmd_mux use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_76cq3gq;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.rsp_demux use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_2ewhqri;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.rsp_mux use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_oqwb4xa;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq.avalon_st_adapter use gidel_hawkeye_pcie_altera_avalon_st_adapter_181.gidel_hawkeye_pcie_altera_avalon_st_adapter_181_f3s2n2q;
endconfig

