config gidel_hawkeye_pcie_altera_mm_interconnect_181_bbwzt2q_cfg;
		design gidel_hawkeye_pcie_altera_mm_interconnect_181_bbwzt2q;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bbwzt2q.pcie_a10_hip_0_rxm_bar0_translator use gidel_hawkeye_pcie_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_bbwzt2q.pcie_a10_hip_0_txs_translator use gidel_hawkeye_pcie_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
endconfig

