config gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii_cfg;
		design gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_rd_dcm_master_translator use gidel_hawkeye_pcie_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_wr_dcm_master_translator use gidel_hawkeye_pcie_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_txs_translator use gidel_hawkeye_pcie_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_rd_dcm_master_agent use gidel_hawkeye_pcie_altera_merlin_master_agent_181.altera_merlin_master_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_wr_dcm_master_agent use gidel_hawkeye_pcie_altera_merlin_master_agent_181.altera_merlin_master_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_txs_agent use gidel_hawkeye_pcie_altera_merlin_slave_agent_181.altera_merlin_slave_agent;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.pcie_a10_hip_0_txs_agent_rsp_fifo use gidel_hawkeye_pcie_altera_avalon_sc_fifo_181.altera_avalon_sc_fifo;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.router use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_4dt2doi;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.router_001 use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_4dt2doi;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.router_002 use gidel_hawkeye_pcie_altera_merlin_router_181.gidel_hawkeye_pcie_altera_merlin_router_181_kvk5vhi;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.cmd_demux use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_r3jh6ri;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.cmd_demux_001 use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_r3jh6ri;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.cmd_mux use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_lc6jfcq;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.rsp_demux use gidel_hawkeye_pcie_altera_merlin_demultiplexer_181.gidel_hawkeye_pcie_altera_merlin_demultiplexer_181_zt4cdzy;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.rsp_mux use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_p6dluzq;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.rsp_mux_001 use gidel_hawkeye_pcie_altera_merlin_multiplexer_181.gidel_hawkeye_pcie_altera_merlin_multiplexer_181_p6dluzq;
		instance gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii.avalon_st_adapter use gidel_hawkeye_pcie_altera_avalon_st_adapter_181.gidel_hawkeye_pcie_altera_avalon_st_adapter_181_ujoah5y;
endconfig

