config gidel_hawkeye_pcie_cfg;
		design gidel_hawkeye_pcie;
		instance gidel_hawkeye_pcie.onchip_memory2_0 use gidel_hawkeye_pcie_altera_avalon_onchip_memory2_181.gidel_hawkeye_pcie_altera_avalon_onchip_memory2_181_wz354my;
		instance gidel_hawkeye_pcie.pcie_a10_hip_0 use gidel_hawkeye_pcie_altera_pcie_a10_hip_181.gidel_hawkeye_pcie_altera_pcie_a10_hip_181_6fghqvy;
		instance gidel_hawkeye_pcie.mm_interconnect_0 use gidel_hawkeye_pcie_altera_mm_interconnect_181.gidel_hawkeye_pcie_altera_mm_interconnect_181_3d7dpjy;
		instance gidel_hawkeye_pcie.mm_interconnect_1 use gidel_hawkeye_pcie_altera_mm_interconnect_181.gidel_hawkeye_pcie_altera_mm_interconnect_181_bifmriq;
		instance gidel_hawkeye_pcie.mm_interconnect_2 use gidel_hawkeye_pcie_altera_mm_interconnect_181.gidel_hawkeye_pcie_altera_mm_interconnect_181_r6n65ii;
		instance gidel_hawkeye_pcie.rst_controller use gidel_hawkeye_pcie_altera_reset_controller_181.altera_reset_controller;
endconfig

