	gidel_hawkeye_pcie u0 (
		.pcie_a10_hip_0_hip_ctrl_test_in          (<connected-to-pcie_a10_hip_0_hip_ctrl_test_in>),          //   pcie_a10_hip_0_hip_ctrl.test_in
		.pcie_a10_hip_0_hip_ctrl_simu_mode_pipe   (<connected-to-pcie_a10_hip_0_hip_ctrl_simu_mode_pipe>),   //                          .simu_mode_pipe
		.pcie_a10_hip_0_hip_pipe_sim_pipe_pclk_in (<connected-to-pcie_a10_hip_0_hip_pipe_sim_pipe_pclk_in>), //   pcie_a10_hip_0_hip_pipe.sim_pipe_pclk_in
		.pcie_a10_hip_0_hip_pipe_sim_pipe_rate    (<connected-to-pcie_a10_hip_0_hip_pipe_sim_pipe_rate>),    //                          .sim_pipe_rate
		.pcie_a10_hip_0_hip_pipe_sim_ltssmstate   (<connected-to-pcie_a10_hip_0_hip_pipe_sim_ltssmstate>),   //                          .sim_ltssmstate
		.pcie_a10_hip_0_hip_pipe_eidleinfersel0   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel0>),   //                          .eidleinfersel0
		.pcie_a10_hip_0_hip_pipe_eidleinfersel1   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel1>),   //                          .eidleinfersel1
		.pcie_a10_hip_0_hip_pipe_eidleinfersel2   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel2>),   //                          .eidleinfersel2
		.pcie_a10_hip_0_hip_pipe_eidleinfersel3   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel3>),   //                          .eidleinfersel3
		.pcie_a10_hip_0_hip_pipe_eidleinfersel4   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel4>),   //                          .eidleinfersel4
		.pcie_a10_hip_0_hip_pipe_eidleinfersel5   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel5>),   //                          .eidleinfersel5
		.pcie_a10_hip_0_hip_pipe_eidleinfersel6   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel6>),   //                          .eidleinfersel6
		.pcie_a10_hip_0_hip_pipe_eidleinfersel7   (<connected-to-pcie_a10_hip_0_hip_pipe_eidleinfersel7>),   //                          .eidleinfersel7
		.pcie_a10_hip_0_hip_pipe_powerdown0       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown0>),       //                          .powerdown0
		.pcie_a10_hip_0_hip_pipe_powerdown1       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown1>),       //                          .powerdown1
		.pcie_a10_hip_0_hip_pipe_powerdown2       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown2>),       //                          .powerdown2
		.pcie_a10_hip_0_hip_pipe_powerdown3       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown3>),       //                          .powerdown3
		.pcie_a10_hip_0_hip_pipe_powerdown4       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown4>),       //                          .powerdown4
		.pcie_a10_hip_0_hip_pipe_powerdown5       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown5>),       //                          .powerdown5
		.pcie_a10_hip_0_hip_pipe_powerdown6       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown6>),       //                          .powerdown6
		.pcie_a10_hip_0_hip_pipe_powerdown7       (<connected-to-pcie_a10_hip_0_hip_pipe_powerdown7>),       //                          .powerdown7
		.pcie_a10_hip_0_hip_pipe_rxpolarity0      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity0>),      //                          .rxpolarity0
		.pcie_a10_hip_0_hip_pipe_rxpolarity1      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity1>),      //                          .rxpolarity1
		.pcie_a10_hip_0_hip_pipe_rxpolarity2      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity2>),      //                          .rxpolarity2
		.pcie_a10_hip_0_hip_pipe_rxpolarity3      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity3>),      //                          .rxpolarity3
		.pcie_a10_hip_0_hip_pipe_rxpolarity4      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity4>),      //                          .rxpolarity4
		.pcie_a10_hip_0_hip_pipe_rxpolarity5      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity5>),      //                          .rxpolarity5
		.pcie_a10_hip_0_hip_pipe_rxpolarity6      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity6>),      //                          .rxpolarity6
		.pcie_a10_hip_0_hip_pipe_rxpolarity7      (<connected-to-pcie_a10_hip_0_hip_pipe_rxpolarity7>),      //                          .rxpolarity7
		.pcie_a10_hip_0_hip_pipe_txcompl0         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl0>),         //                          .txcompl0
		.pcie_a10_hip_0_hip_pipe_txcompl1         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl1>),         //                          .txcompl1
		.pcie_a10_hip_0_hip_pipe_txcompl2         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl2>),         //                          .txcompl2
		.pcie_a10_hip_0_hip_pipe_txcompl3         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl3>),         //                          .txcompl3
		.pcie_a10_hip_0_hip_pipe_txcompl4         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl4>),         //                          .txcompl4
		.pcie_a10_hip_0_hip_pipe_txcompl5         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl5>),         //                          .txcompl5
		.pcie_a10_hip_0_hip_pipe_txcompl6         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl6>),         //                          .txcompl6
		.pcie_a10_hip_0_hip_pipe_txcompl7         (<connected-to-pcie_a10_hip_0_hip_pipe_txcompl7>),         //                          .txcompl7
		.pcie_a10_hip_0_hip_pipe_txdata0          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata0>),          //                          .txdata0
		.pcie_a10_hip_0_hip_pipe_txdata1          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata1>),          //                          .txdata1
		.pcie_a10_hip_0_hip_pipe_txdata2          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata2>),          //                          .txdata2
		.pcie_a10_hip_0_hip_pipe_txdata3          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata3>),          //                          .txdata3
		.pcie_a10_hip_0_hip_pipe_txdata4          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata4>),          //                          .txdata4
		.pcie_a10_hip_0_hip_pipe_txdata5          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata5>),          //                          .txdata5
		.pcie_a10_hip_0_hip_pipe_txdata6          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata6>),          //                          .txdata6
		.pcie_a10_hip_0_hip_pipe_txdata7          (<connected-to-pcie_a10_hip_0_hip_pipe_txdata7>),          //                          .txdata7
		.pcie_a10_hip_0_hip_pipe_txdatak0         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak0>),         //                          .txdatak0
		.pcie_a10_hip_0_hip_pipe_txdatak1         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak1>),         //                          .txdatak1
		.pcie_a10_hip_0_hip_pipe_txdatak2         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak2>),         //                          .txdatak2
		.pcie_a10_hip_0_hip_pipe_txdatak3         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak3>),         //                          .txdatak3
		.pcie_a10_hip_0_hip_pipe_txdatak4         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak4>),         //                          .txdatak4
		.pcie_a10_hip_0_hip_pipe_txdatak5         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak5>),         //                          .txdatak5
		.pcie_a10_hip_0_hip_pipe_txdatak6         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak6>),         //                          .txdatak6
		.pcie_a10_hip_0_hip_pipe_txdatak7         (<connected-to-pcie_a10_hip_0_hip_pipe_txdatak7>),         //                          .txdatak7
		.pcie_a10_hip_0_hip_pipe_txdetectrx0      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx0>),      //                          .txdetectrx0
		.pcie_a10_hip_0_hip_pipe_txdetectrx1      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx1>),      //                          .txdetectrx1
		.pcie_a10_hip_0_hip_pipe_txdetectrx2      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx2>),      //                          .txdetectrx2
		.pcie_a10_hip_0_hip_pipe_txdetectrx3      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx3>),      //                          .txdetectrx3
		.pcie_a10_hip_0_hip_pipe_txdetectrx4      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx4>),      //                          .txdetectrx4
		.pcie_a10_hip_0_hip_pipe_txdetectrx5      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx5>),      //                          .txdetectrx5
		.pcie_a10_hip_0_hip_pipe_txdetectrx6      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx6>),      //                          .txdetectrx6
		.pcie_a10_hip_0_hip_pipe_txdetectrx7      (<connected-to-pcie_a10_hip_0_hip_pipe_txdetectrx7>),      //                          .txdetectrx7
		.pcie_a10_hip_0_hip_pipe_txelecidle0      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle0>),      //                          .txelecidle0
		.pcie_a10_hip_0_hip_pipe_txelecidle1      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle1>),      //                          .txelecidle1
		.pcie_a10_hip_0_hip_pipe_txelecidle2      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle2>),      //                          .txelecidle2
		.pcie_a10_hip_0_hip_pipe_txelecidle3      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle3>),      //                          .txelecidle3
		.pcie_a10_hip_0_hip_pipe_txelecidle4      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle4>),      //                          .txelecidle4
		.pcie_a10_hip_0_hip_pipe_txelecidle5      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle5>),      //                          .txelecidle5
		.pcie_a10_hip_0_hip_pipe_txelecidle6      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle6>),      //                          .txelecidle6
		.pcie_a10_hip_0_hip_pipe_txelecidle7      (<connected-to-pcie_a10_hip_0_hip_pipe_txelecidle7>),      //                          .txelecidle7
		.pcie_a10_hip_0_hip_pipe_txdeemph0        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph0>),        //                          .txdeemph0
		.pcie_a10_hip_0_hip_pipe_txdeemph1        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph1>),        //                          .txdeemph1
		.pcie_a10_hip_0_hip_pipe_txdeemph2        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph2>),        //                          .txdeemph2
		.pcie_a10_hip_0_hip_pipe_txdeemph3        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph3>),        //                          .txdeemph3
		.pcie_a10_hip_0_hip_pipe_txdeemph4        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph4>),        //                          .txdeemph4
		.pcie_a10_hip_0_hip_pipe_txdeemph5        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph5>),        //                          .txdeemph5
		.pcie_a10_hip_0_hip_pipe_txdeemph6        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph6>),        //                          .txdeemph6
		.pcie_a10_hip_0_hip_pipe_txdeemph7        (<connected-to-pcie_a10_hip_0_hip_pipe_txdeemph7>),        //                          .txdeemph7
		.pcie_a10_hip_0_hip_pipe_txmargin0        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin0>),        //                          .txmargin0
		.pcie_a10_hip_0_hip_pipe_txmargin1        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin1>),        //                          .txmargin1
		.pcie_a10_hip_0_hip_pipe_txmargin2        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin2>),        //                          .txmargin2
		.pcie_a10_hip_0_hip_pipe_txmargin3        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin3>),        //                          .txmargin3
		.pcie_a10_hip_0_hip_pipe_txmargin4        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin4>),        //                          .txmargin4
		.pcie_a10_hip_0_hip_pipe_txmargin5        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin5>),        //                          .txmargin5
		.pcie_a10_hip_0_hip_pipe_txmargin6        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin6>),        //                          .txmargin6
		.pcie_a10_hip_0_hip_pipe_txmargin7        (<connected-to-pcie_a10_hip_0_hip_pipe_txmargin7>),        //                          .txmargin7
		.pcie_a10_hip_0_hip_pipe_txswing0         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing0>),         //                          .txswing0
		.pcie_a10_hip_0_hip_pipe_txswing1         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing1>),         //                          .txswing1
		.pcie_a10_hip_0_hip_pipe_txswing2         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing2>),         //                          .txswing2
		.pcie_a10_hip_0_hip_pipe_txswing3         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing3>),         //                          .txswing3
		.pcie_a10_hip_0_hip_pipe_txswing4         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing4>),         //                          .txswing4
		.pcie_a10_hip_0_hip_pipe_txswing5         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing5>),         //                          .txswing5
		.pcie_a10_hip_0_hip_pipe_txswing6         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing6>),         //                          .txswing6
		.pcie_a10_hip_0_hip_pipe_txswing7         (<connected-to-pcie_a10_hip_0_hip_pipe_txswing7>),         //                          .txswing7
		.pcie_a10_hip_0_hip_pipe_phystatus0       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus0>),       //                          .phystatus0
		.pcie_a10_hip_0_hip_pipe_phystatus1       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus1>),       //                          .phystatus1
		.pcie_a10_hip_0_hip_pipe_phystatus2       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus2>),       //                          .phystatus2
		.pcie_a10_hip_0_hip_pipe_phystatus3       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus3>),       //                          .phystatus3
		.pcie_a10_hip_0_hip_pipe_phystatus4       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus4>),       //                          .phystatus4
		.pcie_a10_hip_0_hip_pipe_phystatus5       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus5>),       //                          .phystatus5
		.pcie_a10_hip_0_hip_pipe_phystatus6       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus6>),       //                          .phystatus6
		.pcie_a10_hip_0_hip_pipe_phystatus7       (<connected-to-pcie_a10_hip_0_hip_pipe_phystatus7>),       //                          .phystatus7
		.pcie_a10_hip_0_hip_pipe_rxdata0          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata0>),          //                          .rxdata0
		.pcie_a10_hip_0_hip_pipe_rxdata1          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata1>),          //                          .rxdata1
		.pcie_a10_hip_0_hip_pipe_rxdata2          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata2>),          //                          .rxdata2
		.pcie_a10_hip_0_hip_pipe_rxdata3          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata3>),          //                          .rxdata3
		.pcie_a10_hip_0_hip_pipe_rxdata4          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata4>),          //                          .rxdata4
		.pcie_a10_hip_0_hip_pipe_rxdata5          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata5>),          //                          .rxdata5
		.pcie_a10_hip_0_hip_pipe_rxdata6          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata6>),          //                          .rxdata6
		.pcie_a10_hip_0_hip_pipe_rxdata7          (<connected-to-pcie_a10_hip_0_hip_pipe_rxdata7>),          //                          .rxdata7
		.pcie_a10_hip_0_hip_pipe_rxdatak0         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak0>),         //                          .rxdatak0
		.pcie_a10_hip_0_hip_pipe_rxdatak1         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak1>),         //                          .rxdatak1
		.pcie_a10_hip_0_hip_pipe_rxdatak2         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak2>),         //                          .rxdatak2
		.pcie_a10_hip_0_hip_pipe_rxdatak3         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak3>),         //                          .rxdatak3
		.pcie_a10_hip_0_hip_pipe_rxdatak4         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak4>),         //                          .rxdatak4
		.pcie_a10_hip_0_hip_pipe_rxdatak5         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak5>),         //                          .rxdatak5
		.pcie_a10_hip_0_hip_pipe_rxdatak6         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak6>),         //                          .rxdatak6
		.pcie_a10_hip_0_hip_pipe_rxdatak7         (<connected-to-pcie_a10_hip_0_hip_pipe_rxdatak7>),         //                          .rxdatak7
		.pcie_a10_hip_0_hip_pipe_rxelecidle0      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle0>),      //                          .rxelecidle0
		.pcie_a10_hip_0_hip_pipe_rxelecidle1      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle1>),      //                          .rxelecidle1
		.pcie_a10_hip_0_hip_pipe_rxelecidle2      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle2>),      //                          .rxelecidle2
		.pcie_a10_hip_0_hip_pipe_rxelecidle3      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle3>),      //                          .rxelecidle3
		.pcie_a10_hip_0_hip_pipe_rxelecidle4      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle4>),      //                          .rxelecidle4
		.pcie_a10_hip_0_hip_pipe_rxelecidle5      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle5>),      //                          .rxelecidle5
		.pcie_a10_hip_0_hip_pipe_rxelecidle6      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle6>),      //                          .rxelecidle6
		.pcie_a10_hip_0_hip_pipe_rxelecidle7      (<connected-to-pcie_a10_hip_0_hip_pipe_rxelecidle7>),      //                          .rxelecidle7
		.pcie_a10_hip_0_hip_pipe_rxstatus0        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus0>),        //                          .rxstatus0
		.pcie_a10_hip_0_hip_pipe_rxstatus1        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus1>),        //                          .rxstatus1
		.pcie_a10_hip_0_hip_pipe_rxstatus2        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus2>),        //                          .rxstatus2
		.pcie_a10_hip_0_hip_pipe_rxstatus3        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus3>),        //                          .rxstatus3
		.pcie_a10_hip_0_hip_pipe_rxstatus4        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus4>),        //                          .rxstatus4
		.pcie_a10_hip_0_hip_pipe_rxstatus5        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus5>),        //                          .rxstatus5
		.pcie_a10_hip_0_hip_pipe_rxstatus6        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus6>),        //                          .rxstatus6
		.pcie_a10_hip_0_hip_pipe_rxstatus7        (<connected-to-pcie_a10_hip_0_hip_pipe_rxstatus7>),        //                          .rxstatus7
		.pcie_a10_hip_0_hip_pipe_rxvalid0         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid0>),         //                          .rxvalid0
		.pcie_a10_hip_0_hip_pipe_rxvalid1         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid1>),         //                          .rxvalid1
		.pcie_a10_hip_0_hip_pipe_rxvalid2         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid2>),         //                          .rxvalid2
		.pcie_a10_hip_0_hip_pipe_rxvalid3         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid3>),         //                          .rxvalid3
		.pcie_a10_hip_0_hip_pipe_rxvalid4         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid4>),         //                          .rxvalid4
		.pcie_a10_hip_0_hip_pipe_rxvalid5         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid5>),         //                          .rxvalid5
		.pcie_a10_hip_0_hip_pipe_rxvalid6         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid6>),         //                          .rxvalid6
		.pcie_a10_hip_0_hip_pipe_rxvalid7         (<connected-to-pcie_a10_hip_0_hip_pipe_rxvalid7>),         //                          .rxvalid7
		.pcie_a10_hip_0_hip_pipe_rxdataskip0      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip0>),      //                          .rxdataskip0
		.pcie_a10_hip_0_hip_pipe_rxdataskip1      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip1>),      //                          .rxdataskip1
		.pcie_a10_hip_0_hip_pipe_rxdataskip2      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip2>),      //                          .rxdataskip2
		.pcie_a10_hip_0_hip_pipe_rxdataskip3      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip3>),      //                          .rxdataskip3
		.pcie_a10_hip_0_hip_pipe_rxdataskip4      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip4>),      //                          .rxdataskip4
		.pcie_a10_hip_0_hip_pipe_rxdataskip5      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip5>),      //                          .rxdataskip5
		.pcie_a10_hip_0_hip_pipe_rxdataskip6      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip6>),      //                          .rxdataskip6
		.pcie_a10_hip_0_hip_pipe_rxdataskip7      (<connected-to-pcie_a10_hip_0_hip_pipe_rxdataskip7>),      //                          .rxdataskip7
		.pcie_a10_hip_0_hip_pipe_rxblkst0         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst0>),         //                          .rxblkst0
		.pcie_a10_hip_0_hip_pipe_rxblkst1         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst1>),         //                          .rxblkst1
		.pcie_a10_hip_0_hip_pipe_rxblkst2         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst2>),         //                          .rxblkst2
		.pcie_a10_hip_0_hip_pipe_rxblkst3         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst3>),         //                          .rxblkst3
		.pcie_a10_hip_0_hip_pipe_rxblkst4         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst4>),         //                          .rxblkst4
		.pcie_a10_hip_0_hip_pipe_rxblkst5         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst5>),         //                          .rxblkst5
		.pcie_a10_hip_0_hip_pipe_rxblkst6         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst6>),         //                          .rxblkst6
		.pcie_a10_hip_0_hip_pipe_rxblkst7         (<connected-to-pcie_a10_hip_0_hip_pipe_rxblkst7>),         //                          .rxblkst7
		.pcie_a10_hip_0_hip_pipe_rxsynchd0        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd0>),        //                          .rxsynchd0
		.pcie_a10_hip_0_hip_pipe_rxsynchd1        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd1>),        //                          .rxsynchd1
		.pcie_a10_hip_0_hip_pipe_rxsynchd2        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd2>),        //                          .rxsynchd2
		.pcie_a10_hip_0_hip_pipe_rxsynchd3        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd3>),        //                          .rxsynchd3
		.pcie_a10_hip_0_hip_pipe_rxsynchd4        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd4>),        //                          .rxsynchd4
		.pcie_a10_hip_0_hip_pipe_rxsynchd5        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd5>),        //                          .rxsynchd5
		.pcie_a10_hip_0_hip_pipe_rxsynchd6        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd6>),        //                          .rxsynchd6
		.pcie_a10_hip_0_hip_pipe_rxsynchd7        (<connected-to-pcie_a10_hip_0_hip_pipe_rxsynchd7>),        //                          .rxsynchd7
		.pcie_a10_hip_0_hip_pipe_currentcoeff0    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff0>),    //                          .currentcoeff0
		.pcie_a10_hip_0_hip_pipe_currentcoeff1    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff1>),    //                          .currentcoeff1
		.pcie_a10_hip_0_hip_pipe_currentcoeff2    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff2>),    //                          .currentcoeff2
		.pcie_a10_hip_0_hip_pipe_currentcoeff3    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff3>),    //                          .currentcoeff3
		.pcie_a10_hip_0_hip_pipe_currentcoeff4    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff4>),    //                          .currentcoeff4
		.pcie_a10_hip_0_hip_pipe_currentcoeff5    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff5>),    //                          .currentcoeff5
		.pcie_a10_hip_0_hip_pipe_currentcoeff6    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff6>),    //                          .currentcoeff6
		.pcie_a10_hip_0_hip_pipe_currentcoeff7    (<connected-to-pcie_a10_hip_0_hip_pipe_currentcoeff7>),    //                          .currentcoeff7
		.pcie_a10_hip_0_hip_pipe_currentrxpreset0 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset0>), //                          .currentrxpreset0
		.pcie_a10_hip_0_hip_pipe_currentrxpreset1 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset1>), //                          .currentrxpreset1
		.pcie_a10_hip_0_hip_pipe_currentrxpreset2 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset2>), //                          .currentrxpreset2
		.pcie_a10_hip_0_hip_pipe_currentrxpreset3 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset3>), //                          .currentrxpreset3
		.pcie_a10_hip_0_hip_pipe_currentrxpreset4 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset4>), //                          .currentrxpreset4
		.pcie_a10_hip_0_hip_pipe_currentrxpreset5 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset5>), //                          .currentrxpreset5
		.pcie_a10_hip_0_hip_pipe_currentrxpreset6 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset6>), //                          .currentrxpreset6
		.pcie_a10_hip_0_hip_pipe_currentrxpreset7 (<connected-to-pcie_a10_hip_0_hip_pipe_currentrxpreset7>), //                          .currentrxpreset7
		.pcie_a10_hip_0_hip_pipe_txsynchd0        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd0>),        //                          .txsynchd0
		.pcie_a10_hip_0_hip_pipe_txsynchd1        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd1>),        //                          .txsynchd1
		.pcie_a10_hip_0_hip_pipe_txsynchd2        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd2>),        //                          .txsynchd2
		.pcie_a10_hip_0_hip_pipe_txsynchd3        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd3>),        //                          .txsynchd3
		.pcie_a10_hip_0_hip_pipe_txsynchd4        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd4>),        //                          .txsynchd4
		.pcie_a10_hip_0_hip_pipe_txsynchd5        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd5>),        //                          .txsynchd5
		.pcie_a10_hip_0_hip_pipe_txsynchd6        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd6>),        //                          .txsynchd6
		.pcie_a10_hip_0_hip_pipe_txsynchd7        (<connected-to-pcie_a10_hip_0_hip_pipe_txsynchd7>),        //                          .txsynchd7
		.pcie_a10_hip_0_hip_pipe_txblkst0         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst0>),         //                          .txblkst0
		.pcie_a10_hip_0_hip_pipe_txblkst1         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst1>),         //                          .txblkst1
		.pcie_a10_hip_0_hip_pipe_txblkst2         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst2>),         //                          .txblkst2
		.pcie_a10_hip_0_hip_pipe_txblkst3         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst3>),         //                          .txblkst3
		.pcie_a10_hip_0_hip_pipe_txblkst4         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst4>),         //                          .txblkst4
		.pcie_a10_hip_0_hip_pipe_txblkst5         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst5>),         //                          .txblkst5
		.pcie_a10_hip_0_hip_pipe_txblkst6         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst6>),         //                          .txblkst6
		.pcie_a10_hip_0_hip_pipe_txblkst7         (<connected-to-pcie_a10_hip_0_hip_pipe_txblkst7>),         //                          .txblkst7
		.pcie_a10_hip_0_hip_pipe_txdataskip0      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip0>),      //                          .txdataskip0
		.pcie_a10_hip_0_hip_pipe_txdataskip1      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip1>),      //                          .txdataskip1
		.pcie_a10_hip_0_hip_pipe_txdataskip2      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip2>),      //                          .txdataskip2
		.pcie_a10_hip_0_hip_pipe_txdataskip3      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip3>),      //                          .txdataskip3
		.pcie_a10_hip_0_hip_pipe_txdataskip4      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip4>),      //                          .txdataskip4
		.pcie_a10_hip_0_hip_pipe_txdataskip5      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip5>),      //                          .txdataskip5
		.pcie_a10_hip_0_hip_pipe_txdataskip6      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip6>),      //                          .txdataskip6
		.pcie_a10_hip_0_hip_pipe_txdataskip7      (<connected-to-pcie_a10_hip_0_hip_pipe_txdataskip7>),      //                          .txdataskip7
		.pcie_a10_hip_0_hip_pipe_rate0            (<connected-to-pcie_a10_hip_0_hip_pipe_rate0>),            //                          .rate0
		.pcie_a10_hip_0_hip_pipe_rate1            (<connected-to-pcie_a10_hip_0_hip_pipe_rate1>),            //                          .rate1
		.pcie_a10_hip_0_hip_pipe_rate2            (<connected-to-pcie_a10_hip_0_hip_pipe_rate2>),            //                          .rate2
		.pcie_a10_hip_0_hip_pipe_rate3            (<connected-to-pcie_a10_hip_0_hip_pipe_rate3>),            //                          .rate3
		.pcie_a10_hip_0_hip_pipe_rate4            (<connected-to-pcie_a10_hip_0_hip_pipe_rate4>),            //                          .rate4
		.pcie_a10_hip_0_hip_pipe_rate5            (<connected-to-pcie_a10_hip_0_hip_pipe_rate5>),            //                          .rate5
		.pcie_a10_hip_0_hip_pipe_rate6            (<connected-to-pcie_a10_hip_0_hip_pipe_rate6>),            //                          .rate6
		.pcie_a10_hip_0_hip_pipe_rate7            (<connected-to-pcie_a10_hip_0_hip_pipe_rate7>),            //                          .rate7
		.pcie_a10_hip_0_hip_serial_rx_in0         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in0>),         // pcie_a10_hip_0_hip_serial.rx_in0
		.pcie_a10_hip_0_hip_serial_rx_in1         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in1>),         //                          .rx_in1
		.pcie_a10_hip_0_hip_serial_rx_in2         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in2>),         //                          .rx_in2
		.pcie_a10_hip_0_hip_serial_rx_in3         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in3>),         //                          .rx_in3
		.pcie_a10_hip_0_hip_serial_rx_in4         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in4>),         //                          .rx_in4
		.pcie_a10_hip_0_hip_serial_rx_in5         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in5>),         //                          .rx_in5
		.pcie_a10_hip_0_hip_serial_rx_in6         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in6>),         //                          .rx_in6
		.pcie_a10_hip_0_hip_serial_rx_in7         (<connected-to-pcie_a10_hip_0_hip_serial_rx_in7>),         //                          .rx_in7
		.pcie_a10_hip_0_hip_serial_tx_out0        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out0>),        //                          .tx_out0
		.pcie_a10_hip_0_hip_serial_tx_out1        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out1>),        //                          .tx_out1
		.pcie_a10_hip_0_hip_serial_tx_out2        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out2>),        //                          .tx_out2
		.pcie_a10_hip_0_hip_serial_tx_out3        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out3>),        //                          .tx_out3
		.pcie_a10_hip_0_hip_serial_tx_out4        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out4>),        //                          .tx_out4
		.pcie_a10_hip_0_hip_serial_tx_out5        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out5>),        //                          .tx_out5
		.pcie_a10_hip_0_hip_serial_tx_out6        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out6>),        //                          .tx_out6
		.pcie_a10_hip_0_hip_serial_tx_out7        (<connected-to-pcie_a10_hip_0_hip_serial_tx_out7>),        //                          .tx_out7
		.pcie_a10_hip_0_npor_npor                 (<connected-to-pcie_a10_hip_0_npor_npor>),                 //       pcie_a10_hip_0_npor.npor
		.pcie_a10_hip_0_npor_pin_perst            (<connected-to-pcie_a10_hip_0_npor_pin_perst>),            //                          .pin_perst
		.refclk_clk                               (<connected-to-refclk_clk>)                                //                    refclk.clk
	);

