config gidel_hawkeye_pcie_altera_avalon_st_adapter_181_4htxdaa_cfg;
		design gidel_hawkeye_pcie_altera_avalon_st_adapter_181_4htxdaa;
		instance gidel_hawkeye_pcie_altera_avalon_st_adapter_181_4htxdaa.error_adapter_0 use gidel_hawkeye_pcie_error_adapter_181.gidel_hawkeye_pcie_error_adapter_181_nw5grea;
endconfig

