config gidel_hawkeye_pcie_altera_avalon_st_adapter_181_5kl3u4y_cfg;
		design gidel_hawkeye_pcie_altera_avalon_st_adapter_181_5kl3u4y;
		instance gidel_hawkeye_pcie_altera_avalon_st_adapter_181_5kl3u4y.error_adapter_0 use gidel_hawkeye_pcie_error_adapter_181.gidel_hawkeye_pcie_error_adapter_181_rr5nq7i;
endconfig

