config gidel_hawkeye_pcie_altera_avalon_st_adapter_181_ujoah5y_cfg;
		design gidel_hawkeye_pcie_altera_avalon_st_adapter_181_ujoah5y;
		instance gidel_hawkeye_pcie_altera_avalon_st_adapter_181_ujoah5y.error_adapter_0 use gidel_hawkeye_pcie_error_adapter_181.gidel_hawkeye_pcie_error_adapter_181_6bjmpii;
endconfig

